# fly.toml app configuration file generated for phonebook-practice-homework on 2025-05-28T16:36:53+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'phonebook-practice-homework'
primary_region = 'nrt'

[build]

[env]
  PORT = '8001'

[http_service]
  internal_port = 8001
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
